spring.application.name=FJSN_ZGE_ABG_Proyecto_TFC_01

server.port=9008

#para mysql 8 bbdd nombbdd,
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/tienda_online?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
#no pass spring.datasource.password=,

#JWT 
jwt.secret=C9fKx3Lq7VbP2nT8yZcW4rXsA6dGhJkLmQpRtUvWxYz1234567890AbCdEfGhIj
jwt.expiration-ms=86400000

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

#Incorporacion de SWAGGER -> buscar esta url en el navegador, ya incorporado en POM
# http://localhost:9008/swagger-ui/index.html